name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# Исправленные права доступа
permissions:
  contents: write
  pages: write

# Отменяет запущенные сборки, если прилетел новый пуш в эту же ветку
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npx tsc -b && npx vite build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.nikita-markovskii.dev # Лучше указать с www, если в Cloudflare настроен редирект